### ISSUE TITLE
Satel Integra ETHM 1 Plus - Connection lost, no reconnection 

### ISSUE THREAD

**Issue by grubymisiek** [c-soft/satel_integra#7]
The problem was already mentioned in HA group, there is no reconnection after a network breakdown. It happens every time, it's ease to trace.

[https://github.com/home-assistant/home-assistant/issues/19361](https://github.com/home-assistant/home-assistant/issues/19361)

**Comment by c-soft** [comment]
I have fix for the issue.
If you're interested in testing it before official release, please download this zip: https://www.dropbox.com/s/q3363q9lqofbiwk/satel_integra.zip?dl=0

... and unzip the contents to your `config\homeassistant\components` directory.

Then restart the HomeAassistant 
Fixed: 
* reconnect after network loss
* alarm state initiailized properly
* added "pending" status

Official release will take a moment. Please raise remarks and issues on Github.

**Comment by pa0los** [comment]
Is this fix already in latest release (0.3.4)?

**Comment by c-soft** [comment]
Yes, it's fixed.
