### ISSUE TITLE
Unknow status

### ISSUE THREAD

**Issue by pepeEL** [c-soft/satel_integra#8]
I put you new version to test to folder /config/Homeassistant/components/satel_integra and again after some restart has status alarm UNKNOWN.

**Comment by djxela** [comment]
OK. Component loaded:
You are using a custom component for satel_integra which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

Still state is still unknown, but I dont see previous error in log file.
My logger configuration:
`logger: default: warning logs: homeassistant.components.satel_integra: debug satel_integra.satel_integra: debug`)

**Comment by c-soft** [comment]
Interesting.... What's your platform? 
Please all necessary information.
Is it possible that this has anything to do with the fact that your path to the contains "Homeassistant" with capital letter? 
Also, please attach logs, and quote full path you have put the component in. 
Thank you!

**Comment by c-soft** [comment]
As written before: overloading custom_components only works for 0.88 and up.
Please try there and it should work.
Closing for now.
